title: Tyler Hayes
email: tylerxhayes@gmail.com
lastUpdated: "02/22/19"
url: "http://tylerhayes.xyz"

markdown: kramdown

defaults:

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - readme.md
  - node_modules
  - package.json
  - package-lock.json
  - gulpfile.js
