title: Tyler Hayes
email: tylerxhayes@gmail.com
lastUpdated: "02/10/19"
url: "http://tylerhayes.xyz"

markdown: kramdown

defaults:
  - scope:
      path: "assets/gallery"
    values:
      image: true

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
